server:
  port: 8080
spring:
  cloud:
    gateway:
      globalcors:
        add-to-simple-url-handler-mapping: true
        corsConfigurations:
          '[/**]':
            allowedOriginPatterns:
              - '*'
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders:
              - '*'
            exposedHeaders:
              - '*'
            allowCredentials: true
            maxAge: 3600
      routes:
        - id: doctor-service
          uri: http://localhost:8081
          predicates:
            - Path=/doctors/**
        - id: patient-service
          uri: http://localhost:8082
          predicates:
            - Path=/patients/**
        - id: appointment-service
          uri: http://localhost:8083
          predicates:
            - Path=/appointments/**
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
  main:
    web-application-type: reactive
